[package]
name = "ec-executor"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
log = "0.4.8"
codec = { package = "parity-scale-codec", version = "1.3.4" }

sp-version = { version = "2.0.0" }
sp-core = { version = "2.0.0" }

sc-executor = { version = "0.8.0" }

[dev-dependencies]
