[package]
name = "ec-rpc"
version = "0.1.0"
authors = ["patract labs <https://github.com/patractlabs>"]
edition = "2018"

[dependencies]
jsonrpc-core = { version = "15.0.0" }
jsonrpc-core-client = { version = "15.0.0" }
jsonrpc-derive = "15.0.0"
serde = { version = "1.0.101", features = ["derive"] }
hex = "0.4"

sp-utils = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-blockchain = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

sc-client-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }

ec-client-api = { path = "../api" }
